### ISSUE TITLE
No way to disable assertions

### ISSUE THREAD

**Issue by geotre** [floooh/sokol-nim#24]
[this file](https://github.com/floooh/sokol-nim/blob/239444a288518f8af476889fcd906bceb32a7750/src/sokol/c/sokol_defines.h#L5) defines `SOKOL_ASSERT` in a way that cannot be disabled, meaning that even in release mode it is not possible to turn off assertions and reduce calls to e.g. `glGetError`. Compiling with `--passC:-DNDEBUG` does not have an effect as it would with C/C++ usage of Sokol.

I would propose wrapping in a similar check to `assert.h`:

```c
#ifndef NDEBUG
    #define SOKOL_ASSERT...
#endif
```

We may want to also check if the Nim app is compiled in release mode, in which case we can pass `-DNDEBUG` when compiling `sokol_gfx.c`

**Comment by floooh** [comment]
Merged, many thanks for the PR! (I have a small question in the PR though, nothing critical though)
