### ISSUE TITLE
Generated converters have incorrect assertions

### ISSUE THREAD

**Issue by geotre** [floooh/sokol-nim#26]
The Nim bindings generator creates converters for many types that contain a static assert, e.g.:

```nim
converter toPassActioncolors*[N:static[int]](items: array[N, ColorAttachmentAction]): array[4, ColorAttachmentAction] =
  static: assert(N < 4)
  for index,item in items.pairs: result[index]=item
```

The assert needs to be `<=` not `<` right?

Opening a PR

**Comment by floooh** [comment]
Yeah looks like a got that wrong. Thanks for the PR, will merge right away.

**Comment by floooh** [comment]
Closing ticket because PR has been merged.
